import type { Applicant, Job } from "@/types";

export const applicants: Applicant[] = [
  {
    id: "maya-chen",
    hasAnalysis: true,
    name: "Maya Chen",
    email: "maya.chen@example.com",
    phone: "+1 (415) 555-0142",
    position: "Senior Product Designer",
    score: 94,
    status: "Shortlisted",
    appliedAt: "Jun 5, 2026",
    education: "BFA, Interaction Design, California College of the Arts",
    experience: "7 years",
    location: "San Francisco, CA",
    summary:
      "Senior product designer with deep B2B SaaS experience and a strong record of shipping complex workflow products.",
    strengths: [
      "Exceptional systems thinking",
      "Strong portfolio of enterprise workflows",
      "Experienced cross-functional leader",
    ],
    weaknesses: ["Limited fintech domain exposure", "Salary expectations may be above range"],
    matchedSkills: ["Figma", "Design Systems", "User Research", "Prototyping", "B2B SaaS"],
    missingSkills: ["Fintech", "Amplitude"],
    recommendation:
      "Strongly recommend advancing to the portfolio interview. Maya's experience closely matches the role's core requirements.",
  },
  {
    id: "ethan-wright",
    hasAnalysis: true,
    name: "Ethan Wright",
    email: "ethan.wright@example.com",
    phone: "+1 (206) 555-0188",
    position: "Frontend Engineer",
    score: 91,
    status: "Interview",
    appliedAt: "Jun 4, 2026",
    education: "BS, Computer Science, University of Washington",
    experience: "6 years",
    location: "Seattle, WA",
    summary:
      "Frontend specialist with extensive React, TypeScript, and design systems experience across high-growth SaaS products.",
    strengths: ["Advanced React expertise", "Excellent accessibility practices", "Strong product intuition"],
    weaknesses: ["Limited backend ownership", "No direct AI product experience"],
    matchedSkills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Playwright"],
    missingSkills: ["Python", "LLM tooling"],
    recommendation:
      "Advance to technical interview. Ethan is an excellent fit for the frontend scope and raises the quality bar.",
  },
  {
    id: "sofia-rodriguez",
    hasAnalysis: true,
    name: "Sofia Rodriguez",
    email: "sofia.r@example.com",
    phone: "+1 (512) 555-0173",
    position: "Product Manager",
    score: 88,
    status: "Under Review",
    appliedAt: "Jun 4, 2026",
    education: "MBA, UT Austin; BS, Information Systems",
    experience: "8 years",
    location: "Austin, TX",
    summary:
      "Data-oriented product manager with experience building automation products for mid-market customers.",
    strengths: ["Clear product strategy", "Strong analytics", "Excellent stakeholder management"],
    weaknesses: ["Less hands-on in early-stage environments"],
    matchedSkills: ["Product Strategy", "Analytics", "B2B SaaS", "Roadmapping"],
    missingSkills: ["Recruiting Tech"],
    recommendation: "Proceed to recruiter screen with emphasis on early-stage operating style.",
  },
  {
    id: "noah-williams",
    hasAnalysis: true,
    name: "Noah Williams",
    email: "noah.w@example.com",
    phone: "+1 (312) 555-0165",
    position: "Backend Engineer",
    score: 86,
    status: "New",
    appliedAt: "Jun 3, 2026",
    education: "MS, Computer Science, Northwestern University",
    experience: "5 years",
    location: "Chicago, IL",
    summary:
      "Backend engineer focused on Python services, data pipelines, and reliable cloud infrastructure.",
    strengths: ["Strong Python foundation", "Production API experience", "Thoughtful system design"],
    weaknesses: ["Limited PostgreSQL optimization examples"],
    matchedSkills: ["Python", "FastAPI", "AWS", "Docker", "Redis"],
    missingSkills: ["Supabase", "Gemini API"],
    recommendation: "Advance to technical screen and explore database depth.",
  },
  {
    id: "olivia-patel",
    hasAnalysis: true,
    name: "Olivia Patel",
    email: "olivia.patel@example.com",
    phone: "+1 (646) 555-0111",
    position: "Frontend Engineer",
    score: 83,
    status: "Under Review",
    appliedAt: "Jun 2, 2026",
    education: "BS, Software Engineering, RIT",
    experience: "4 years",
    location: "New York, NY",
    summary: "Product-minded frontend engineer experienced in React applications and component libraries.",
    strengths: ["Polished UI implementation", "Strong collaboration", "Good testing habits"],
    weaknesses: ["Less experience at enterprise scale"],
    matchedSkills: ["React", "TypeScript", "Storybook", "Cypress"],
    missingSkills: ["Next.js", "Recharts"],
    recommendation: "Keep in active review; portfolio demonstrates strong execution.",
  },
  {
    id: "liam-kim",
    hasAnalysis: true,
    name: "Liam Kim",
    email: "liam.kim@example.com",
    phone: "+1 (213) 555-0199",
    position: "AI Engineer",
    score: 79,
    status: "New",
    appliedAt: "Jun 1, 2026",
    education: "MS, Artificial Intelligence, USC",
    experience: "3 years",
    location: "Los Angeles, CA",
    summary: "AI engineer with practical RAG, evaluation, and model integration experience.",
    strengths: ["Current LLM expertise", "Strong experimentation habits"],
    weaknesses: ["Limited production leadership", "Shorter professional track record"],
    matchedSkills: ["Python", "RAG", "Gemini", "Evaluation"],
    missingSkills: ["FastAPI", "Team Leadership"],
    recommendation: "Consider for a mid-level role or continue with a focused technical screen.",
  },
  {
    id: "ava-thompson",
    hasAnalysis: true,
    name: "Ava Thompson",
    email: "ava.t@example.com",
    phone: "+1 (617) 555-0134",
    position: "Product Manager",
    score: 72,
    status: "Rejected",
    appliedAt: "May 30, 2026",
    education: "BA, Economics, Boston University",
    experience: "3 years",
    location: "Boston, MA",
    summary: "Associate product manager with consumer marketplace experience.",
    strengths: ["Customer empathy", "Clear communication"],
    weaknesses: ["Insufficient B2B experience", "Limited ownership scope"],
    matchedSkills: ["Research", "Roadmapping"],
    missingSkills: ["B2B SaaS", "Analytics", "Automation"],
    recommendation: "Not recommended for this senior opening; retain for future associate roles.",
  },
];

export const jobs: Job[] = [
  {
    id: "senior-product-designer",
    title: "Senior Product Designer",
    department: "Product",
    location: "San Francisco / Remote",
    type: "Full-time",
    description:
      "Lead end-to-end product design for TalentFlow's core recruiting workflows and evolving design system.",
    skills: ["Figma", "Design Systems", "User Research", "Prototyping", "B2B SaaS"],
    createdAt: "May 14, 2026",
    applicants: 48,
    status: "Active",
  },
  {
    id: "frontend-engineer",
    title: "Frontend Engineer",
    department: "Engineering",
    location: "Remote, US",
    type: "Full-time",
    description:
      "Build fast, accessible recruiter experiences using React, TypeScript, Next.js, and our component system.",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Testing"],
    createdAt: "May 18, 2026",
    applicants: 64,
    status: "Active",
  },
  {
    id: "backend-engineer",
    title: "Backend Engineer",
    department: "Engineering",
    location: "Remote, US",
    type: "Full-time",
    description: "Design reliable APIs and data pipelines powering our recruitment automation platform.",
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "AWS"],
    createdAt: "May 20, 2026",
    applicants: 37,
    status: "Active",
  },
  {
    id: "product-manager",
    title: "Product Manager",
    department: "Product",
    location: "New York / Remote",
    type: "Full-time",
    description: "Own the roadmap for intelligent candidate discovery and recruiter productivity.",
    skills: ["Product Strategy", "Analytics", "B2B SaaS", "Roadmapping"],
    createdAt: "May 25, 2026",
    applicants: 29,
    status: "Active",
  },
  {
    id: "ai-engineer",
    title: "AI Engineer",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    description: "Develop, evaluate, and operate AI features for resume intelligence and recruiter assistance.",
    skills: ["Python", "LLMs", "RAG", "Evaluation", "FastAPI"],
    createdAt: "May 28, 2026",
    applicants: 22,
    status: "Draft",
  },
];

export const monthlyApplications = [
  { month: "Jan", applications: 86, shortlisted: 18 },
  { month: "Feb", applications: 104, shortlisted: 23 },
  { month: "Mar", applications: 97, shortlisted: 21 },
  { month: "Apr", applications: 132, shortlisted: 31 },
  { month: "May", applications: 148, shortlisted: 38 },
  { month: "Jun", applications: 76, shortlisted: 19 },
];

export const statusDistribution = [
  { name: "New", value: 52, color: "#2563EB" },
  { name: "Under Review", value: 74, color: "#F59E0B" },
  { name: "Shortlisted", value: 38, color: "#22C55E" },
  { name: "Interview", value: 24, color: "#8B5CF6" },
  { name: "Rejected", value: 59, color: "#CBD5E1" },
];

export const skillsData = [
  { skill: "React", candidates: 68 },
  { skill: "TypeScript", candidates: 57 },
  { skill: "Python", candidates: 49 },
  { skill: "Product", candidates: 41 },
  { skill: "Figma", candidates: 35 },
];
